In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

In [2]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [5]:
path = '/content/gdrive/My Drive/Colab Notebooks/Modern Artificial Intelligence/Emotion AI Dataset/'

In [6]:
!ls

gdrive	sample_data


In [18]:
data = os.path.join(path, 'data.csv')

In [19]:
df = pd.read_csv(data)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2140 entries, 0 to 2139
Data columns (total 31 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   left_eye_center_x          2140 non-null   float64
 1   left_eye_center_y          2140 non-null   float64
 2   right_eye_center_x         2140 non-null   float64
 3   right_eye_center_y         2140 non-null   float64
 4   left_eye_inner_corner_x    2140 non-null   float64
 5   left_eye_inner_corner_y    2140 non-null   float64
 6   left_eye_outer_corner_x    2140 non-null   float64
 7   left_eye_outer_corner_y    2140 non-null   float64
 8   right_eye_inner_corner_x   2140 non-null   float64
 9   right_eye_inner_corner_y   2140 non-null   float64
 10  right_eye_outer_corner_x   2140 non-null   float64
 11  right_eye_outer_corner_y   2140 non-null   float64
 12  left_eyebrow_inner_end_x   2140 non-null   float64
 13  left_eyebrow_inner_end_y   2140 non-null   float

In [20]:
df.head()

left_eye_center_x  ...                                              Image
0          66.033564  ...  238 236 237 238 240 240 239 241 241 243 240 23...
1          64.332936  ...  219 215 204 196 204 211 212 200 180 168 178 19...
2          65.057053  ...  144 142 159 180 188 188 184 180 167 132 84 59 ...
3          65.225739  ...  193 192 193 194 194 194 193 192 168 111 50 12 ...
4          66.725301  ...  147 148 160 196 215 214 216 217 219 220 206 18...

[5 rows x 31 columns]

In [21]:
df.head().T

0  ...                                                  4
left_eye_center_x                                                    66.0336  ...                                            66.7253
left_eye_center_y                                                    39.0023  ...                                            39.6213
right_eye_center_x                                                    30.227  ...                                            32.2448
right_eye_center_y                                                   36.4217  ...                                             38.042
left_eye_inner_corner_x                                              59.5821  ...                                            58.5659
left_eye_inner_corner_y                                              39.6474  ...                                            39.6213
left_eye_outer_corner_x                                              73.1303  ...                                            72.5159
left_eye_outer_corner_y                                                39.97  ...                                            39.8845
right_eye_inner_corner_x                                             36.3566  ...                                            36.9824
right_eye_inner_corner_y                                             37.3894  ...                                            39.0949
right_eye_outer_corner_x                                             23.4529  ...                                            22.5061
right_eye_outer_corner_y                                             37.3894  ...                                            38.3052
left_eyebrow_inner_end_x                                             56.9533  ...                                            57.2496
left_eyebrow_inner_end_y                                             29.0336  ...                                            30.6722
left_eyebrow_outer_end_x                                             80.2271  ...                                            77.7629
left_eyebrow_outer_end_y                                             32.2281  ...                                            31.7372
right_eyebrow_inner_end_x                                            40.2276  ...                                            38.0354
right_eyebrow_inner_end_y                                            29.0023  ...                                            30.9354
right_eyebrow_outer_end_x                                            16.3564  ...                                            15.9259
right_eyebrow_outer_end_y                                            29.6475  ...                                            30.6722
nose_tip_x                                                           44.4206  ...                                            43.2995
nose_tip_y                                                           57.0668  ...                                            64.8895
mouth_left_corner_x                                                  61.1953  ...                                            60.6714
mouth_left_corner_y                                                  79.9702  ...                                            77.5232
mouth_right_corner_x                                                 28.6145  ...                                            31.1918
mouth_right_corner_y                                                  77.389  ...                                            76.9973
mouth_center_top_lip_x                                               43.3126  ...                                            44.9627
mouth_center_top_lip_y                                               72.9355  ...                                            73.7074
mouth_center_bottom_lip_x                                            43.1307  ...                                            44.2271
mouth_center_bottom_lip_y                                            84.4858  ...    

In [22]:
df.head().T.tail()

0  ...                                                  4
mouth_center_top_lip_x                                               43.3126  ...                                            44.9627
mouth_center_top_lip_y                                               72.9355  ...                                            73.7074
mouth_center_bottom_lip_x                                            43.1307  ...                                            44.2271
mouth_center_bottom_lip_y                                            84.4858  ...                                            86.8712
Image                      238 236 237 238 240 240 239 241 241 243 240 23...  ...  147 148 160 196 215 214 216 217 219 220 206 18...

[5 rows x 5 columns]

In [23]:
# df.shape
# (2140, 31)

# print(type(df['Image']))
# <class 'pandas.core.series.Series'>

# len(df['Image'][0])
# 33593

# df['Image'][0][0]
# '2'

# type(df['Image'][0][0])
# str

# df['Image'][0][3]
# ' '

# type(df['Image'][0][3])
# str

In [24]:
X = df['Image'].str.split(' ')

# print(type(X))
# <class 'pandas.core.series.Series'>

# len(X)
# 2140

# len(X[0])
# 9216

# X[0][0]
# '238'

# type(X[0][0])
# str

# X[0][3]
# '238'

# type(X[0][3])
# str

In [36]:
# print(X[0])
# ['238' '236' '237' ...  '70'  '75'  '90']

In [37]:
# print(X[1])
# ['219' '215' '204' ...   '1'   '1'   '1']

In [29]:
input_list = []

for i in range(len(X)):
  input_list.append(X[i])

inputs = np.array(input_list, dtype=int)

In [34]:
# print(inputs[0])
# [238 236 237 ...  70  75  90]

In [35]:
# print(inputs[1])
# [219 215 204 ...   1   1   1]

In [33]:
# print(type(inputs))
# <class 'numpy.ndarray'>

# len(inputs)
# 2140

# len(inputs[0])
# 9216

# inputs[0][0]
# 238

# type(inputs[0][0])
# numpy.int64

# inputs[0][3]
# 238

# type(inputs[0][3])
# numpy.int64

In [ ]:
Y = (df.drop(columns='Image', axis=1)).values

# print(Y.shape)
# (2140, 30)

# print(type(Y))
# <class 'numpy.ndarray'>

In [ ]:
HOW TO RESHAPE ALL TO 96, 96

96

In [ ]:
# df['Image'].dtype
# dtype('O')

# type(df['Image'])
# pandas.core.series.Series

In [ ]:
df['Image'].apply(len)

0       96
1       96
2       96
3       96
4       96
        ..
2135    96
2136    96
2137    96
2138    96
2139    96
Name: Image, Length: 2140, dtype: int64

In [ ]:
# type(df['Image'][0][0])
# str

# type(df['Image'][0][3])
# str

# df['Image'][0][0]
# '2'

# df['Image'][0][3]
# ' '

In [ ]:
df['Image'] = df['Image'].apply(lambda x: np.fromstring(x, dtype = int, sep = ' ').reshape(96, 96))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  """Entry point for launching an IPython kernel.


ValueError: ignored

In [ ]:
# df['Image'][0][0]

# array([238, 236, 237, 238, 240, 240, 239, 241, 241, 243, 240, 239, 231,
#        212, 190, 173, 148, 122, 104,  92,  79,  73,  74,  73,  73,  74,
#         81,  74,  60,  64,  75,  86,  93, 102, 100, 105, 109, 114, 121,
#        127, 132, 134, 137, 137, 140, 139, 138, 137, 137, 140, 141, 143,
#        144, 147, 148, 149, 147, 147, 148, 145, 147, 144, 146, 147, 147,
#        143, 134, 130, 130, 128, 116, 104,  98,  90,  82,  78,  85,  88,
#         86,  80,  77,  87, 108, 111, 115, 128, 133, 188, 242, 252, 250,
#        248, 251, 250, 250, 250])

# type(df['Image'][0][0][0])
# numpy.int64

# type(df['Image'][0][0][3])
# numpy.int64

# df['Image'][0][0][0]
# 238

# df['Image'][0][0][3]
# 238

In [ ]:
df['Image'].apply(len)

In [ ]:
df['Image'][0].shape

In [ ]:
plt.imshow(df['Image'][0], cmap='gray')